### ISSUE TITLE
Altum LWIR implementation

### ISSUE THREAD

**Issue by ArtKata** [filipematias23/FIELDimageR-Workshop-11#1]
Hello,

I'm wondering if it is possible to analyze MicaSense Altum LWIR images in the FieldImageR. I've been trying to select the band but without success. Perhaps there are ways to implement it? 
Amazing package, absolutely love it, great work Filipe!

Best,
Artūrs Katamadze

**Comment by filipematias23** [comment]
Hi Arturs,

Thanks for your feedback and for contacting us... Yes, you can.

The secret is to trick the package and select any other layer/band when the function asks for R, G, B, RedEdge, or NIR. For example, you can call the thermal layer on RedEdge=4.

There is a community working together and answering questions at the FIELDimageR Forum: [https://groups.google.com/forum/#!forum/fieldimager](https://groups.google.com/forum/#!forum/fieldimager) 

You can share examples and code over there… ok

Hope it helps.
All the best,
Filipe

**Comment by ArtKata** [comment]
Hey,

Thanks for the reply, I will move this topic to the google groups,
didnt know such a thing existed :D
I think you can remove this thread in github to keep it clean.

Best,
Artūrs
